# Before `make install' is performed this script should be runnable with
# `make test'. After `make install' it should work as `perl ERModule.t'

#########################

# change 'tests => 2' to 'tests => last_test_to_print';

use Test::More tests => 2;
BEGIN { use_ok('ERModule') };


my $fail = 0;
foreach my $constname (qw(
	ER__CHUNK_TYPE__BAKE ER__CHUNK_TYPE__RS ER__CHUNK_TYPE__SHD
	ER__CONTENT_DELETE ER__CONTENT_PRINT ER__CONTENT_SAVE
	ER__CONTENT_STATE__ADD ER__CONTENT_STATE__DELETE
	ER__DECLARE__FRAME_BLOCK ER__DECLARE__FRAME_BLOCK_OUTSIDE
	ER__DECLARE__NO_FRAME
	ER__ENUM_RIB_BOX__DECLARE__JUST_BEFORE_FIRST_FRAME_BEGIN
	ER__ENUM_RIB_BOX__FRAME__JUST_BEFORE_DISPLAY
	ER__ENUM_RIB_BOX__FRAME__JUST_BEFORE_WORLD_BEGIN
	ER__ENUM_RIB_BOX__LIGHT__JUST_AFTER_ATTRIBUTE
	ER__ENUM_RIB_BOX__OBJECT__JUST_AFTER_ATTRIBUTE
	ER__ENUM_RIB_BOX__OBJECT__JUST_BEFORE_GEOMETRIC_PRIMITIVE
	ER__ENUM_RIB_BOX__OBJECT__JUST_BEFORE_LIGHT_SHADER
	ER__ENUM_RIB_BOX__OBJECT__JUST_BEFORE_SURFACE_SHADER
	ER__ENUM_RIB_BOX__WORLD__JUST_AFTER_LAST_OBJECT_BLOCK
	ER__ENUM_RIB_BOX__WORLD__JUST_BEFORE_FIRST_GEOMETRIC_PRIMITIVE_BLOCK
	ER__ENUM_RIB_BOX__WORLD__JUST_BEFORE_FIRST_LIGHTSOURCE_BLOCK
	ER__ENUM_RIB_DIRECTIVE__ATTRIBUTE
	ER__ENUM_RIB_DIRECTIVE__ATTRIBUTE_BEGIN
	ER__ENUM_RIB_DIRECTIVE__ATTRIBUTE_END
	ER__ENUM_RIB_DIRECTIVE__DISPLACEMENT ER__ENUM_RIB_DIRECTIVE__DISPLAY
	ER__ENUM_RIB_DIRECTIVE__DONT_CARE ER__ENUM_RIB_DIRECTIVE__FRAME_BEGIN
	ER__ENUM_RIB_DIRECTIVE__FRAME_END
	ER__ENUM_RIB_DIRECTIVE__GEOMETRIC_PRIMITIVE
	ER__ENUM_RIB_DIRECTIVE__LIGHTSOURCE ER__ENUM_RIB_DIRECTIVE__SURFACE
	ER__ENUM_RIB_DIRECTIVE__TRANSFORM_BEGIN
	ER__ENUM_RIB_DIRECTIVE__TRANSFORM_END
	ER__ENUM_RIB_DIRECTIVE__WORLD_BEGIN ER__ENUM_RIB_DIRECTIVE__WORLD_END
	ER__GET_RIB_DIRECTIVE__EOF ER__GET_RIB_DIRECTIVE__EXCEPTION
	ER__GET_RIB_DIRECTIVE__UNKNOWN ER__GET_RIB_DIRECTIVE__VALID
	ER__RS__CAST_SHADOW ER__RS__DELETE ER__RS__MATTE ER__RS__RECV_SHADOW
	ER__RS__RT ER__RS__SSSC ER__RS__VISIBILITY ER__RS__VIS_REFL
	ER__RS__VIS_REFR ER__SHADER_TYPE__LIGHTSOURCE ER__SHADER_TYPE__SURFACE
	ER__STACK_TYPE__ATTRIBUTE ER__STACK_TYPE__FRAME
	ER__STACK_TYPE__TRANSFORM ER__VAR_SCOPE__ALL ER__VAR_SCOPE__GLOBAL
	ER__VAR_SCOPE__JOB_CHUNK)) {
  next if (eval "my \$a = $constname; 1");
  if ($@ =~ /^Your vendor has not defined ERModule macro $constname/) {
    print "# pass: $@";
  } else {
    print "# fail: $@";
    $fail = 1;
  }

}

ok( $fail == 0 , 'Constants' );
#########################

# Insert your test code below, the Test::More module is use()ed here so read
# its man page ( perldoc Test::More ) for help writing this test script.

